mvno/Franz

README.md, docs/tools/templates/template.cshtml
Replace ProjectScaffold README template with Franz content
Remove link not used from website
=> Update readme and website

src/Franz/Brokers.fs, src/Franz/HighLevel.fs
To aviod inifite waiting on connections
=> Add receive timeout

src/Franz/HighLevel.fs
Allow setting consumer options, and fix bug with heavy load consumer
=> Allowing setting consumer options

RELEASE_NOTES.md, src/Franz/HighLevel.fs
Handle offset out of range exception, by asking for the earliest offset when getting this error, and start consuming from this position
=> Handle offset out of range exception

RELEASE_NOTES.md, src/Franz/Brokers.fs
Catch exception for now, allowing the MailboxProcessor to continue it's work
=> Handle that all brokers are unavailable

Franz.sln, RELEASE_NOTES.md, src/Franz/HighLevel.fs
Add support for consumer and producing to/from a subset of partitions
=> Partition subset

RELEASE_NOTES.md, src/Franz/HighLevel.fs, src/Franz/Messages.fs
Add support for batching multiple messages in one produce request
=> Message batching

RELEASE_NOTES.md, src/Franz/Brokers.fs, src/Franz/HighLevel.fs, src/Franz/Messages.fs, src/Franz/Stream.fs
It should not be neccessary to inject the consumer offset manager into the consumer.
=> Improve offset handling

src/Franz/Brokers.fs
=> Make function tail recursive

src/Franz/Brokers.fs
When reusing BrokerRouter we would try to connect to the cluster multiple times. This is now fixed by checking if we're already connected
=> Fix connect bug

RELEASE_NOTES.md, paket.dependencies, paket.lock, src/Franz/Compression.fs, src/Franz/Franz.fsproj, src/Franz/HighLevel.fs, src/Franz/Messages.fs, src/Franz/paket.references, tests/Franz.Tests/CompressionTest.fs, tests/Franz.Tests/Franz.Tests.fsproj, tests/Franz.Tests/paket.references
Add support for GZip and Snappy compression
=> Support compression

src/Franz/Brokers.fs
Update log levels from trace -> info
+
Added fatal on inability to get broker. This might be a bad thing so please have a closer look :)
=> Update log levels

src/Franz/Brokers.fs
Suggestion to downgrade to warning in places where we appear to try again.
Please read changes carefully :).
=> Downgrade from Error to warning

src/Franz/Brokers.fs, src/Franz/Stream.fs
Adjustments to log level.
Notice that the changes to getMetadata and findBroker should be carefully examined.
=> Adjustwarninglevels

src/Franz/Brokers.fs, src/Franz/HighLevel.fs
Introdue retry on RequestTimedOut + add new and known exceptions
=> Request timed out handling

RELEASE_NOTES.md, src/Franz/Brokers.fs, src/Franz/Franz.fsproj, src/Franz/HighLevel.fs, src/Franz/Infrastructure.fs, src/Franz/Logging.fs, src/Franz/Stream.fs, src/Franz/TcpClient.fs, src/Franz/Zookeeper.fs
This introduces support for using the Zookeeper cluster to get information about the Kafka servers.
We have had several issues where information from the Kafka cluster was out of sync with the Zookeeper, resulting in unexpected behavior.
=> Zookeeper support

src/Franz/Messages.fs
Fix some errors in the protocol
=> Fix consumer group protocol

src/Franz/HighLevel.fs
If no key has been specified insert empty string
=> Handle messages with null key

src/Franz/Messages.fs, tests/Franz.Integration.Tests/ApiVersionTest.fs, tests/Franz.Integration.Tests/Cluster.fs, tests/Franz.Integration.Tests/Franz.Integration.Tests.fsproj
=> Support ApiVersion request

RELEASE_NOTES.md, build.fsx, src/Franz/Brokers.fs, src/Franz/Consumer.fs, src/Franz/Messages.fs, src/Franz/Producer.fs, tests/Franz.Integration.Tests/Cluster.fs, tests/Franz.Integration.Tests/Franz.Integration.Tests.fsproj, tests/Franz.Integration.Tests/RecoveryTest.fs
Add some tests for recovery scenarios, and fix some of the bugs found
=> Recovery integration tests
